### ISSUE TITLE
Event only displays new data in state after hard refresh

### ISSUE THREAD

**Issue by l-suzuki** [zachmandeville/dathering#5]

**Comment by zachmandeville** [comment]
This has been fixed in latest commit.  Here's the current flow, to doublecheck:

**Prep:**
1. clone this repo to yr computer.
2. remove all text from `party.json` if there is anything there.
3. add the whole folder as a new dat site in Beaker, then open this dat site.

**Action**
1. You will see an unstyled form for you to put event details into it.
2. when you click submit, a new page appears with the simpsons as a default background image and all the details filled out with what you just entered.
3. You can share this datlink to others and they'll see the same info.
4. You can edit the party.json file and it will reflect these changes on the site.
5. Anyone can fork the site, clear out their party.json file, and get back to the form.
